__author__ = 'priyansh'
from django.conf.urls import patterns,url
from mysiteadmin import views
urlpatterns=patterns('',url(r'^$',views.designation,name='designation'),
                     url(r'^insertDesignation/$',views.insertDesignation,name='insertDesignation'),
                     url(r'^admindesignation/$',views.admindesignation,name='admindesignation'),
                     url(r'^(?P<des_id>\d+)/editDesignation/$',views.editDesignation,name='editDesignation'),
                     url(r'^(?P<des_id>\d+)/updateDesignation/$',views.updateDesignation,name='updateDesignation'),
                     url(r'^(?P<des_id>\d+)/deleteDesignation/$',views.deleteDesignation,name='deleteDesignation'),
                     url(r'^(?P<des_id>\d+)/editAdminDesignation/$',views.editAdminDesignation,name='editAdminDesignation'),
                     url(r'^(?P<des_id>\d+)/updateAdminDesignation/$',views.updateAdminDesignation,name='updateAdminDesignation'),
                     url(r'^(?P<des_id>\d+)/deleteAdminDesignation/$',views.deleteAdminDesignation,name='deleteAdminDesignation'),
                     url(r'^insertAdminDesignation/$',views.insertAdminDesignation,name='insertAdminDesignation'),
                     url(r'^openEmployeeDesignation/$',views.openEmployeeDesignation,name='openEmployeeDesignation'),
                     url(r'^(?P<emp_id>\d+)/changeEmpDes/$',views.changeEmpDes,name='changeEmpDes'),
                     url(r'^updateEmpDesignation/$',views.updateEmpDesignation,name='updateEmpDesignation'),
                     url(r'^openAdminEmployeeDesignation/$',views.openAdminEmployeeDesignation,name='openAdminEmployeeDesignation'),
                     url(r'^(?P<emp_id>\d+)/changeAdminEmpDes/$',views.changeAdminEmpDes,name='changeAdminEmpDes'),
                     url(r'^updateAdminEmpDesignation/$',views.updateAdminEmpDesignation,name='updateAdminEmpDesignation'),
                     url(r'^country/$', views.country, name='country'),
                     url(r'^insertCountry/$', views.insertCountry, name='insertCountry'),
                     url(r'^(?P<country_id>\d+)/editCountry/$',views.editCountry,name='editCountry'),
                     url(r'^(?P<country_id>\d+)/updateCountry/$',views.updateCountry,name='updateCountry'),
                     url(r'^(?P<country_id>\d+)/deleteCountry/$',views.deleteCountry,name='deleteCountry'),
                     url(r'^course/$', views.course, name='course'),
                     url(r'^insertCourse/$', views.insertCourse, name='insertCourse'),
                     url(r'^(?P<course_id>\d+)/editCourse/$',views.editCourse,name='editCourse'),
                     url(r'^(?P<course_id>\d+)/updateCourse/$',views.updateCourse,name='updateCourse'),
                     url(r'^(?P<course_id>\d+)/deleteCourse/$',views.deleteCourse,name='deleteCourse'),
                     url(r'^department/$', views.department, name='department'),
                     url(r'^insertDept/$', views.insertDept, name='insertDept'),
                     url(r'^(?P<dept_id>\d+)/editDept/$',views.editDept,name='editDept'),
                     url(r'^(?P<dept_id>\d+)/updateDept/$',views.updateDept,name='updateDept'),
                     url(r'^(?P<dept_id>\d+)/deleteDept/$',views.deleteDept,name='deleteDept'),
                     url(r'^state/$', views.state, name='state'),
                     url(r'^insertSate/$', views.insertState, name='insertStates'),
                     url(r'^showState/$',views.showState,name='showState'),
                     url(r'^(?P<state_id>\d+)/deleteState/$',views.deleteState,name='deleteState'),
                     url(r'^(?P<state_id>\d+)/editState/$',views.editState,name='editState'),
                     url(r'^(?P<state_id>\d+)/updateState/$',views.updateState,name='updateState'),
                     url(r'^city/$', views.city, name='city'),
                     url(r'^insertCity/$', views.insertCity, name='insertCity'),
                     url(r'^showCity/$', views.showCity, name='showCity'),
                     url(r'^(?P<city_id>\d+)/deleteCity/$', views.deleteCity, name='deleteCity'),
                     url(r'^(?P<city_id>\d+)/editCity/$', views.editCity, name='editCity'),
                     url(r'^(?P<city_id>\d+)/updateCity/$', views.updateCity, name='updateCity'),
)
